---
  - name: update apt packages
    become: true
    apt:
      update_cache: true
  - name: upgrade packages
    become: true
    apt:
      upgrade: true
      
  - name: remove dependency after build up
    become: true
    apt:
      autoremove: yes
  - name: install npm & node
    become: true
    apt:
      name: [npm, nodejs]
      state: latest
      update_cache: true
  - name: install pm2
    become: true
    npm:
      name: pm2
      global: true
      production: true
      state: present
  - name: create a directory
    become: true
    file:
      path: ~/web
      state: directory
  - name: copy file dirrectory
    become: true
    template:
     src: "files/index.js"
     dest: "~/web/index.js"
  - name: Executing Shell
    become: true
    shell: |
      pm2 start ~/web/index.js -f