Description: Deploy a basic server 

Resources:
  UdacityServer:
    Type: AWS::EC2::Instance
    Properties:
      
      EbsOptimized: false
      ImageId: "ami-052efd3df9dad4825"
      SecurityGroups:
        - !Ref Ec2Security
      InstanceType: "t2.micro"
      
  Ec2Security:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "This describe the security group " # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


     
      
  
      