version: 2.1

jobs:
  create_infrastructure:
   docker:
    - image: amazon/aws-cli
   steps:
    - checkout
    - run:
       name: Deploy command
       command: |
            ls -la
            printenv
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack

workflows:
  create-workflow:
    jobs:
      - create_infrastructure
