version: 2.1

jobs:
  create_infrastructure:
   docker:
    - image: amazon/aws-cli
   steps:
    - run:
       name: Deploy command
       command: |
         aws cloudformation deploy \
         --template-file template.yml \
         --stack-name mystack1 \
         --region us-east-1

workflows:
  create-workflow:
    jobs:
      - create_infrastructure
