version: 2.1

jobs:
  create_infrastructure:
   docker:
    - image: amazon/aws-cli
   steps:
    - checkout
    - run:
       name: Deploy command
       command: |
            ls -la
            pwd
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack
  configure_infrastructure:
    docker:
    - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["2c:13:7a:4d:8d:0e:c1:91:81:05:9d:4c:c3:92:25:66"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: run playbook
          command:
            ansible-playbook main.yaml -i udacity_key.pem
            



workflows:
  deploy_infrastructure:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
        requires:
          - create_infrastructure
